### ISSUE TITLE
[SPIKE] Have harbor running on gauss as a GS app in some way (doesn't matter how)?

### ISSUE THREAD

**Issue by ladeoshodi** [giantswarm/harbor-app#62]
Definition of Done:
- Have harbor running on gauss

**Comment by raha-farokhi** [comment]
```
apiVersion: v1
data:
  values: |
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor-tls-prod
          notarySecretName: notary-tls-prod
      ingress:
        ClassName: nginx
        hosts:
          core: core.harbor.g8s.gauss.eu-west-1.aws.gigantic.io
          notary: notary.harbor.g8s.gauss.eu-west-1.aws.gigantic.io
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-giantswarm
          kubernetes.io/tls-acme: "true"
          kubernetes.io/ingress.class: nginx
          ingress.kubernetes.io/force-ssl-redirect: "true"
    externalURL: https://core.harbor.g8s.gauss.eu-west-1.aws.gigantic.io
    internalTLS:
      enabled: true
    persistence:
      enabled: false
kind: ConfigMap
metadata:
  name: harbor-user-values
  namespace: giantswarm
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: harbor
  name: harbor
  namespace: giantswarm   
spec:
  catalog: giantswarm-playground-test
  kubeConfig:
    inCluster: true
  name: harbor
  namespace: giantswarm
  userConfig:
    configMap:
      name: "harbor-user-values"
      namespace: "giantswarm"
```
